python3 metrics-hadesancients.py --METRICS_PATH "D:\metrics_runs\hades_ancients_metrics\runs" --DATABASE hades_ancients --DATABASE_USER postgres --DATABASE_PASSWORD secret --FIND_NEW_RUNS_TO_PROCESS true --PROCESS_RUNS true --REPORT_PATH reports/hadesancients
python3 metrics-hadesancients.py --METRICS_PATH "D:\metrics_runs\hades_ancients_metrics\runs" --DATABASE hades_ancients --DATABASE_USER postgres --DATABASE_PASSWORD secret --FIND_NEW_RUNS_TO_PROCESS true --PROCESS_RUNS true --ONLY_BASE_GAME_CHARACTERS true --REPORT_PATH reports/hadesancients-basegamecharacters
python3 metrics-hadesancients.py --METRICS_PATH "D:\metrics_runs\hades_ancients_metrics\runs" --DATABASE hades_ancients --DATABASE_USER postgres --DATABASE_PASSWORD secret --FIND_NEW_RUNS_TO_PROCESS true --PROCESS_RUNS true --ONLY_BASE_GAME_CHARACTERS true --MIN_ASC_LEVEL 10 --REPORT_PATH reports/hadesancients-basegamecharacters-asc10

python3 metrics-hadesancients-generate-graphs.py --source_directory "reports/hadesancients" --destination_directory "reports/graphs-hadesancients"
python3 metrics-hadesancients-generate-graphs.py --source_directory "reports/hadesancients-basegamecharacters" --destination_directory "reports/graphs-hadesancients-basegamecharacters"
python3 metrics-hadesancients-generate-graphs.py --source_directory "reports/hadesancients-basegamecharacters-asc10" --destination_directory "reports/graphs-hadesancients-basegamecharacters-asc10"


python3 metrics-hadesancients.py --METRICS_PATH "D:\metrics_runs\hades_ancients_metrics\runs" --DATABASE hades_ancients --DATABASE_USER postgres --DATABASE_PASSWORD secret --FIND_NEW_RUNS_TO_PROCESS true --PROCESS_RUNS true --REPORT_PATH reports/v0.7.x/hadesancients --VERSION_PREFIX v0.7
python3 metrics-hadesancients.py --METRICS_PATH "D:\metrics_runs\hades_ancients_metrics\runs" --DATABASE hades_ancients --DATABASE_USER postgres --DATABASE_PASSWORD secret --FIND_NEW_RUNS_TO_PROCESS true --PROCESS_RUNS true --ONLY_BASE_GAME_CHARACTERS true --REPORT_PATH reports/v0.7.x/hadesancients-basegamecharacters --VERSION_PREFIX v0.7
python3 metrics-hadesancients.py --METRICS_PATH "D:\metrics_runs\hades_ancients_metrics\runs" --DATABASE hades_ancients --DATABASE_USER postgres --DATABASE_PASSWORD secret --FIND_NEW_RUNS_TO_PROCESS true --PROCESS_RUNS true --ONLY_BASE_GAME_CHARACTERS true --MIN_ASC_LEVEL 10 --REPORT_PATH reports/v0.7.x/hadesancients-basegamecharacters-asc10 --VERSION_PREFIX v0.7

python3 metrics-hadesancients-generate-graphs.py --source_directory "reports/v0.7.x/hadesancients" --destination_directory "reports/v0.7.x/graphs-hadesancients"
python3 metrics-hadesancients-generate-graphs.py --source_directory "reports/v0.7.x/hadesancients-basegamecharacters" --destination_directory "reports/v0.7.x/graphs-hadesancients-basegamecharacters"
python3 metrics-hadesancients-generate-graphs.py --source_directory "reports/v0.7.x/hadesancients-basegamecharacters-asc10" --destination_directory "reports/v0.7.x/graphs-hadesancients-basegamecharacters-asc10"